force-app/main/default/objects/Candidate_Skill__c/Candidate_Skill__c.object-meta.xml
<CustomObject>
    <label>Candidate Skill</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Candidate Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Candidate Skills</relationshipLabel>
    <relationshipName>Candidate_Skills</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UserSkillSelectorController.cls
/**
 * @description UserSkillSelectorController is controller class for userSkillSelector LWC component
 */
public with sharing class UserSkillSelectorController {
    /**
     * @description Get the list of skills of the selected candidate
     * 
     * @param contactId Id of the Contact record
     * @return List<OptionItem> List of OptionItem records
     */
    @AuraEnabled(cacheable=true)
    public static List<OptionItem> getCandidateSkills(Id contactId){
        List<OptionItem> result = new List<OptionItem>();
        for (Candidate_Skill__c candidateSkill : SkillService.getCandidateSkillsByContactId(contactId)) {
            Map<String, String> valueMap = new Map<String, String> ();
            valueMap.put('skillId', candidateSkill.Skill__c);
            valueMap.put('candidateSkillId', candidateSkill.Id);
            result.add(
                new OptionItem(candidateSkill.Skill__r.Name, valueMap)
            );
        }
        return result;
    }

    /**
     * @description Get the list of all skills
     * 
     * @return List<OptionItem> List of OptionItem records
     */
    @AuraEnabled(cacheable=true)
    public static List<OptionItem> getSkills() {
        List<OptionItem> result = new List<OptionItem>();
        for (Skill__c skill : SkillService.getSkills()) {
            result.add(
                new OptionItem(skill.Name, skill.Id)
            );
        }
        return result;
    }
}