force-app/main/default/objects/Candidate_Skill__c/Candidate_Skill__c.object-meta.xml
<CustomObject>
    <label>Candidate Skill</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Candidate Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Skill__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate Skills</relationshipLabel>
    <relationshipName>Candidate_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Candidate_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Candidate Skills</relationshipLabel>
    <relationshipName>Candidate_Skills</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Job_Position__c/Job_Position__c.object-meta.xml
<CustomObject>
    <label>Job Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Skill__c/Job_Skill__c.object-meta.xml
<CustomObject>
    <label>Job Skill</label>
    <nameField>
        <displayFormat>JS-{000000}</displayFormat>
        <label>Job Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Skill__c/fields/Job_Position__c.field-meta.xml
<CustomField>
    <fullName>Job_Position__c</fullName>
    <label>Job Position</label>
    <referenceTo>Job_Position__c</referenceTo>
    <relationshipLabel>Job Skills</relationshipLabel>
    <relationshipName>Job_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Job Skills</relationshipLabel>
    <relationshipName>Job_Skills</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SkillService.cls
/**
 * @description SkillService class is used to manage the Skill__c, Job_Skill__c, Candidate_Skill__c objects
 */
public with sharing class SkillService {
    /**
     * @description Get the list of skills for the selected candidate
     * 
     * @param Id contactId Id of the Contact record
     * @return List<Candidate_Skill__c> List of Candidate_Skill__c records
     */
    public static List<Candidate_Skill__c> getCandidateSkillsByContactId(Id contactId) {
        return [
            SELECT Id, Candidate__c, Skill__c, Skill__r.Name 
            FROM Candidate_Skill__c 
            WHERE Candidate__c = :contactId 
            ORDER BY Skill__r.Name ASC
        ];
    }

    /**
     * @description Get the list of skills for the selected job
     * 
     * @param Id jobId Id of the Job_Position__c record
     * @return List<Job_Skill__c> List of Job_Skill__c records
     */
    public static List<Job_Skill__c> getJobSkillByJobId(Id jobId) {
        return [
            SELECT Id, Job_Position__c, Skill__c, Skill__r.Name 
            FROM Job_Skill__c 
            WHERE Job_Position__c = :jobId 
            ORDER BY Skill__r.Name ASC
        ];
    }

    /**
     * @description Get the list of all skills
     * 
     * @return List<Skill__c> List of Skill__c records
     */
    public static List<Skill__c> getSkills() {
        return [
            SELECT Id, Name 
            FROM Skill__c 
            ORDER BY Name ASC
        ];
    }
}