force-app/main/default/objects/Candidate_Skill__c/Candidate_Skill__c.object-meta.xml
<CustomObject>
    <label>Candidate Skill</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Candidate Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Skill__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate Skills</relationshipLabel>
    <relationshipName>Candidate_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Candidate_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Candidate Skills</relationshipLabel>
    <relationshipName>Candidate_Skills</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{YYYY}/{MM}/{DD}-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Position__c.field-meta.xml
<CustomField>
    <fullName>Job_Position__c</fullName>
    <label>Job Position</label>
    <referenceTo>Job_Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Job_Position__c/Job_Position__c.object-meta.xml
<CustomObject>
    <label>Job Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Position__c/fields/Is_remote_allowed__c.field-meta.xml
<CustomField>
    <fullName>Is_remote_allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is remote allowed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Salary_from__c.field-meta.xml
<CustomField>
    <fullName>Salary_from__c</fullName>
    <label>Salary from</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Salary_to__c.field-meta.xml
<CustomField>
    <fullName>Salary_to__c</fullName>
    <label>Salary to</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Offer Made</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Skill__c/Job_Skill__c.object-meta.xml
<CustomObject>
    <label>Job Skill</label>
    <nameField>
        <displayFormat>JS-{000000}</displayFormat>
        <label>Job Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Skill__c/fields/Job_Position__c.field-meta.xml
<CustomField>
    <fullName>Job_Position__c</fullName>
    <label>Job Position</label>
    <referenceTo>Job_Position__c</referenceTo>
    <relationshipLabel>Job Skills</relationshipLabel>
    <relationshipName>Job_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Job Skills</relationshipLabel>
    <relationshipName>Job_Skills</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
/**
 * @description TestDataFactory class is used to create test data
 */
public with sharing class TestDataFactory {
    private final static String COMMUNITY_USER_PROFILE = 'Job Seeker Profile'; // Community User profile name
    private final static String STANDARD_USER_PROFILE = 'Standard User'; // Standard User profile name

    /**
     * @description Create a list of Skill__c records
     * 
     * @param numberOfRecords Number of records to create
     * @return List<Skill__c> List of Skill__c records
     */
    public static List<Skill__c> createSkills(Integer numberOfRecords) {
        List<Skill__c> skills = new List<Skill__c>();
        for (Integer i = 0; i < numberOfRecords; i++) {
            Skill__c skill = new Skill__c(Name = 'Skill ' + i);
            skills.add(skill);
        }
        return skills;
    }

    /**
     * @description Create a list of Candidate_Skill__c records
     * 
     * @param numberOfRecords Number of records to create
     * @param candidateId Id of the Candidate (Contact) record
     * @return List<Candidate_Skill__c> List of Candidate_Skill__c records
     */
    public static List<Candidate_Skill__c> createCandidateSkills(Integer numberOfRecords, Id candidateId) {
        List<Skill__c> skills = createSkills(numberOfRecords);
        insert skills;

        List<Candidate_Skill__c> candidateSkills = new List<Candidate_Skill__c>();
        for (Skill__c skill : skills) {
            Candidate_Skill__c candidateSkill = new Candidate_Skill__c(
                Candidate__c = candidateId,
                Skill__c = skill.Id
            );
            candidateSkills.add(candidateSkill);
        }

        return candidateSkills;
    }

    /**
     * @description Create a list of Job_Skill__c records
     * 
     * @param numberOfRecords Number of records to create
     * @param jobPositionId Id of the Job_Position__c record
     * @return List<Job_Skill__c> List of Job_Skill__c records
     */
    public static List<Job_Skill__c> createJobSkills(Integer numberOfRecords, Id jobPositionId) {
        List<Skill__c> skills = createSkills(numberOfRecords);
        insert skills;

        List<Job_Skill__c> jobSkills = new List<Job_Skill__c>();
        for (Skill__c skill : skills) {
            Job_Skill__c jobSkill = new Job_Skill__c(
                Job_Position__c = jobPositionId,
                Skill__c = skill.Id
            );
            jobSkills.add(jobSkill);
        }

        return jobSkills;
    }

    /**
     * @description Create a list of Contact records
     * 
     * @param numberOfRecords Number of records to create
     * @return List<Contact> List of Contact records
     */
    public static List<Contact> createContacts(Integer numberOfRecords) {
        List<Contact> contacts = new List<Contact>();
        for (Integer i = 0; i < numberOfRecords; i++) {
            Contact tempContact = new Contact(
                FirstName = 'Test', 
                LastName = 'Contact ' + i,
                Email = 'test.contact' + i + '@nomail.com',
                Phone = '123456543' + i,
                MailingCity = 'Boston',
                MailingCountry = 'United States'
            );
            contacts.add(tempContact);
        }
        return contacts;
    }

    /**
     * @description Create a list of Account records
     * 
     * @param numberOfRecords Number of records to create
     * @return List<Account> List of Account records
     */
    public static List<Account> createAccounts(Integer numberOfRecords) {
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < numberOfRecords; i++) {
            Account tempAccount = new Account(
                Name = 'Test Account ' + i
            );
            accounts.add(tempAccount);
        }
        return accounts;
    }

    /**
     * @description Create a list of User records with Standard User profile
     * 
     * @param numberOfRecords Number of records to create
     * @return List<User> List of User records
     */
    public static List<User> createUsers(Integer numberOfRecords) {
        Id profileId = [SELECT Id FROM Profile WHERE Name = :STANDARD_USER_PROFILE LIMIT 1]?.Id;
        List<User> users = new List<User>();
        for (Integer i = 0; i < numberOfRecords; i++) {
            User tempUser = new User(
                FirstName = 'Test', 
                LastName = 'User' + i,
                Alias = 'tuser' + i,
                Email = 'testuser' + i + '@nomail.com',
                Username = 'testuser' + i + '@nomail.com',
                CommunityNickname = 'testuser' + i,
                LocaleSidKey = 'en_US',
                TimeZoneSidKey = 'GMT',
                ProfileId = profileId,
                LanguageLocaleKey = 'en_US',
                EmailEncodingKey = 'UTF-8'
            );
            users.add(tempUser);
        }
        return users;
    }

    /**
     * @description Create a list of User records with Community User profile
     * 
     * @param numberOfRecords Number of records to create
     * @return List<User> List of User records
     */
    public static List<User> createCommunityUsers(Integer numberOfRecords) {
        List<Account> commAccounts = createAccounts(numberOfRecords);
        insert commAccounts;

        List<Contact> commContacts = createContacts(numberOfRecords);

        for (Integer i = 0; i < numberOfRecords; i++) {
            commContacts[i].AccountId = commAccounts[i].Id;
        }
        insert commContacts;

        Id profileId = [SELECT Id FROM Profile WHERE Name = :COMMUNITY_USER_PROFILE LIMIT 1]?.Id;
        List<User> commUsers = createUsers(numberOfRecords);

        for (Integer i = 0; i < numberOfRecords; i++) {
            commUsers[i].ContactId = commContacts[i].Id;
            commUsers[i].ProfileId = profileId;
        }

        return commUsers;
    }

    /**
     * @description Create a list of Job_Position__c records
     * 
     * @param numberOfRecords Number of records to create
     * @return List<Job_Position__c> List of Job_Position__c records
     */
    public static List<Job_Position__c> createJobPositions(Integer numberOfRecords) {
        List<Job_Position__c> positions = new List<Job_Position__c>();
        for (Integer i = 0; i < numberOfRecords; i++) {
            Job_Position__c tempPosition = new Job_Position__c(
                Name = 'Test Position ' + i,
                Status__c = 'Open',
                Description__c = 'Test Description',
                Is_remote_allowed__c = true,
                Salary_from__c = 1000 + i * 100,
                Salary_to__c = 1500 + i * 100
            );
            positions.add(tempPosition);
        }
        return positions;
    }

    /**
     * @description Create a Job_Application__c record
     * 
     * @param jobPositionId Id of the Job_Position__c record
     * @param candidateId Id of the Candidate (Contact) record
     * @return Job_Application__c Job_Application__c record
     */
    public static Job_Application__c createJobApplication(Id jobPositionId, Id candidateId) {
        Job_Application__c application = new Job_Application__c(
            Job_Position__c = jobPositionId,
            Candidate__c = candidateId
        );
        return application;
    }

    /**
     * @description Create a ContentVersion record with the text file
     * 
     * @return ContentVersion ContentVersion record
     */
    public static ContentVersion createContentVersion() {
        ContentVersion contVersion = new ContentVersion(
            Title = 'Test',
            PathOnClient = 'Test.txt',
            VersionData = Blob.valueOf('Test Content'),
            Origin = 'C'// A content document from the user’s personal library
        );
        return contVersion;
    }

    /**
     * @description Create a ContentDocumentLink record to link the document and the specified record
     * 
     * @param contentDocumentId Id of the ContentDocument record
     * @param linkedEntityId Id of the record to link to
     * @return ContentDocumentLink ContentDocumentLink record
     */
    public static ContentDocumentLink createContentDocumentLink(Id contentDocumentId, Id linkedEntityId) {
        ContentDocumentLink contDocLink = new ContentDocumentLink(
            ContentDocumentId = contentDocumentId,
            LinkedEntityId = linkedEntityId,
            Visibility = 'AllUsers',
            ShareType = 'V'
        );
        return contDocLink;
    }    
}