force-app/main/default/objects/Job_Position__c/Job_Position__c.object-meta.xml
<CustomObject>
    <label>Job Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Skill__c/Job_Skill__c.object-meta.xml
<CustomObject>
    <label>Job Skill</label>
    <nameField>
        <displayFormat>JS-{000000}</displayFormat>
        <label>Job Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Skill__c/fields/Job_Position__c.field-meta.xml
<CustomField>
    <fullName>Job_Position__c</fullName>
    <label>Job Position</label>
    <referenceTo>Job_Position__c</referenceTo>
    <relationshipLabel>Job Skills</relationshipLabel>
    <relationshipName>Job_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Job Skills</relationshipLabel>
    <relationshipName>Job_Skills</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SkillMatchesController.cls
/**
 * @description SkillMatchesController is controller class for skillMatches LWC component
 */
public with sharing class SkillMatchesController {
    /**
     * @description Get the list of matching skills for the selected job
     * 
     * @param jobId Id of the Job_Position__c record
     * @return List<OptionItem> List of OptionItem records
     */
    @AuraEnabled(cacheable=true)
    public static List<OptionItem> getJobSkills(Id jobId){
        List<OptionItem> result = new List<OptionItem>();
        for (Job_Skill__c jobSkill : SkillService.getJobSkillByJobId(jobId)) {
            result.add(
                new OptionItem(jobSkill.Skill__r.Name, jobSkill.Skill__c)
            );
        }
        return result;
    }
}