force-app/main/default/objects/Job_Position__c/Job_Position__c.object-meta.xml
<CustomObject>
    <label>Job Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Position__c/fields/Is_remote_allowed__c.field-meta.xml
<CustomField>
    <fullName>Is_remote_allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is remote allowed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Number_of_job_applications__c.field-meta.xml
<CustomField>
    <fullName>Number_of_job_applications__c</fullName>
    <label>Number of job applications</label>
    <summaryForeignKey>Job_Application__c.Job_Position__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Salary_from__c.field-meta.xml
<CustomField>
    <fullName>Salary_from__c</fullName>
    <label>Salary from</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Salary_to__c.field-meta.xml
<CustomField>
    <fullName>Salary_to__c</fullName>
    <label>Salary to</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Offer Made</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobPositionsListController.cls
/**
 * @description JobPositionsListController is controller class for jobPositionsList LWC component
 */
public with sharing class JobPositionsListController {
    // Contstant that stores the Open status name for the Status__c field of the Job_Position__c object
    private static final String OPEN_STATUS = 'Open';

    /**
     * @description Get the list of open job positions
     * 
     * @return List<Job_Position__c> List of Job_Position__c records
     */
    @AuraEnabled (cacheable=true)
    public static List<Job_Position__c> getJobPositions(){
        return [
            SELECT 
                Id, CreatedDate, Days_Open__c, Description__c, Is_remote_allowed__c, 
                Name, Number_of_job_applications__c, Salary_from__c, Salary_to__c 
            FROM Job_Position__c 
            WHERE Status__c = :OPEN_STATUS 
            ORDER BY CreatedDate DESC
        ];
    }
}