force-app/main/default/objects/Job_Position__c/Job_Position__c.object-meta.xml
<CustomObject>
    <label>Job Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Offer Made</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobPositionsListControllerTest.cls
/**
 * @description Unit tests for JobPositionsListController class
 */
@isTest
private class JobPositionsListControllerTest {

    /**
     * @description Test method to test the getJobPositions() method.
     *              The method should return all open job positions.
     */
    @isTest
    static void testGetJobPositions() {
        // Create 10 job positions
        List<Job_Position__c> jobPositions = TestDataFactory.createJobPositions(10);
        // Set the status of the first to Closed
        jobPositions[0].Status__c = 'Closed';
        insert jobPositions;

        Test.startTest();
        List<Job_Position__c> returnedJobPositions = JobPositionsListController.getJobPositions();
        Test.stopTest();

        System.assertEquals(jobPositions.size() - 1, returnedJobPositions.size(), 'The method should return only open job positions');
    }
}